### ISSUE TITLE
再測定モードの実装

### ISSUE THREAD

**Issue by Mizunanari** [aizulab/coias-front-app#1]
# 画面構成

正しくは下記

測定/再描画　再測定

# 再測定モードについて

自動検出できなかった小惑星を手動でマーキングするモード

##  手順

小惑星ごとにアップ画像を表示
小惑星のまわり３点の座標を指定（クリック）

(x1, y1) (x2, y2) (x3, y3)

これをもとに四角形を生成する

**Comment by Mizunanari** [comment]
https://github.com/aizulab/COIAS_program_github/blob/main/docs/About_the_coias_program/coias/COIAS%20%E3%81%AE%E4%BD%BF%E3%81%84%E6%96%B9(%E6%89%8B%E5%8B%95%E6%B8%AC%E5%AE%9A%E4%BB%98%E3%81%8D%E7%B7%A8).md

浦川様より

```
少し補足すると0番目は再測定に関わらない一般的なことで、仮符号と既知天体の軌道取得は分けたほうが良いと言う意味。
1.自動測定を実行するという意味。実際は2の工程からが再測定モード。
3.手動（再測定）。ここでは1天体を手動測定しているがBlinkして1枚目に戻って2天体目、3天体目と続けていく。2枚目を始める時は“Same object with previous image”の質問に対してNoを選択。
4.すべての手動（再）測定天体の座標取得が終了したらQuit
5.は説明のとおり。6.アパーチャーとは小惑星の光を測定するエリアのこと。7.XでmatplotlibのGUIを閉じると言う意味。
8.以下は自動測定モードの測定結果ファイルに、手動測定モードの結果を追加する手順。内容は自動測定と同じ。
```

**Comment by Mizunanari** [comment]
@masaaki-y @AnbaiAnbai 

- [x] COIAS.py にて手動で読み込みたい小惑星上でスペースを押し座標を記録

  -> memo2.txtに書き込み
  https://github.com/coias/coias-back-app/blob/main/COIAS.py#L212-L284

- [ ] astsearch_manual(astsearch1Q5.py) でmemo2.textを読み込み

長方形の座標を入力させる
  -> 結果をlistb3.txtに書き込み
  https://github.com/coias/coias-back-app/blob/main/astsearch1Q5.py

- [ ] astsearch_manual(その他、スクリプト)でlistb3.txtから読み込み成形など

  ->結果をmemo.txtに出力
  https://github.com/coias/coias-back-app/blob/main/astsearch_manual

**Comment by Mizunanari** [comment]
@AnbaiAnbai 

# 再測定モード機能実装案

## モードの名称について

再測定モード  ->  手動測定モード

## 各フェイズについて

### フェイズ１

大まかな星の位置を写真から選択する。写真は５枚それぞれから星の中心を選択する。  
操作としては、`星の数 * 写真の枚数`のクリックが必要になる。

### フェイズ２

フェイズ１で選択した星をズームで表示し、より正確な星の位置を３点で囲うように選択する。  
操作としては、`星の数 * 5(写真の枚数) * 3(囲う座標)`のクリックが必要になる。

## 「追加」ボタンを押した時の動作

1. アコーディオンを全て閉じる
2. ツールボックスの項目を一つ増やす
3. 2.で増やしたアコーディオンを開く
4. 一つ前の数字+1をIDに割り振る
5. 写真の１枚目を表示
6. 「手動で測定したい小惑星の中心をクリックしてください」
7. ダイアログで確認
8. 写真２枚め〜５枚めで同操作
9. xy座標を反映し、終了

**Comment by AnbaiAnbai** [comment]
@urakawa-seitaro @COIAS-program 
お疲れ様です。
現在再測定モードの

https://github.com/coias/coias-front-app/issues/1#issuecomment-1090008679

にて記載した、手順で実装しているのですが、現在

> astsearch_manual(astsearch1Q5.py) でmemo2.textを読み込み


を実装途中で、

https://github.com/coias/coias-back-app/blob/5fc87437f0e157426517e5c8273dcc9862edc155/astsearch1Q5.py#L183

`[number, radec1b[0, 0], radec1b[0, 1], radec1b[0, 2], mag1, mage1, xy1[0, 0], ypix - xy1[0, 1], fil1])`

の引数の内容をそれぞれ教えて頂きたいです。

お手数ですがお願い致します。

**Comment by urakawa-seitaro** [comment]
お返事遅れてすいません。
順番に[小惑星の番号（Hではじまる数字。Hは除く）、時刻、赤経（天体の座標）、赤緯（天体の座標）、明るさ、明るさのエラー、fits画像上でのx座標、fits画像上でのy座標、フィルター名]
となっています。
ypix - xy1[0.1]のところは今後少し修正するかもです（値に30pixelを足すかもしれません。）

**Comment by AnbaiAnbai** [comment]
@urakawa-seitaro @COIAS-program 
#51 等で対応させていただきますので、こちらクローズさせていただきます。
