### ISSUE TITLE
全自動処理の処理フローについて

### ISSUE THREAD

**Issue by Mizunanari** [aizulab/coias-front-app#29]
> 軌道取得（仮符号）の次に光源検出となっていますが、処理の進捗がターミナルで見ることができるCentOSで走らせたところビニングマスクの段階で光源検出を行っている感じがします。

https://coiashq.slack.com/archives/C034Z0GDEBX/p1648668035241469?thread_ts=1648652573.604459&cid=C034Z0GDEBX

**Comment by Mizunanari** [comment]
Sugiura Keisuke

>「光源検出」ボタンを消すことと「ビニングマスク」ボタンの名称を「ビニングマスク・光源検出」に変更することに加え、全自動処理ボタンを押した時に軌道取得の後には光源検出をしないようにしなくてはいけません。
具体的には、coias-front-app/ExplorePrepare.jsxの165-169行目を消せばいいのだと思います。
素人ゆえ間違っている可能性があるのでご判断をお願いしたいですが、ご対応お願いいたします。

**Comment by COIAS-program** [comment]
4月7日追記
ディレクトリ構造やファイルの中身が変わっているので、杉浦的怪しい箇所は、

> 具体的には、coias-front-app/src/page/ExplorePrepare.jsxの231-235行目を消せばいいのだと思います。

に変わっています。

**Comment by Mizunanari** [comment]
@COIAS-program 
追記ありがとうございます。
確認いたします。

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
コメントありがとうございました。
[d72b50e](https://github.com/coias/coias-front-app/commit/d72b50e05343ab45ab3e1e6d68acc5fa0428b842)
にて修正させて頂きました。お手数ですがお時間のある時に確認、確認後問題なければ各issueのcloseをお願い致します。

**Comment by COIAS-program** [comment]
光源検出ボタンが消えていること、及び全自動処理のフローから余計な後の光源検出がなくなっていることを確認いたしました。

ただ、全自動処理を行うと添付の画面のように自動検出(くるくる)のまま止まってしまい操作できなくなってしまいます。
最後にできるはずの all.txt が出力されているのでバックのスクリプト的には最後まで行っていると思うので、全自動処理を押した時のフロントの最後の処理の問題で自動検出(くるくる)が止まらなくなっていると思われます。
なお、自動検出ボタンを単体で押した時には問題なく終わるので、全自動処理ボタンの最終処理の問題だと思われます。
よろしくお願い致します。
<img width="1388" alt="スクリーンショット 2022-04-11 12 13 42" src="https://user-images.githubusercontent.com/86390904/162659226-3ccf8144-7b2e-4ee9-a06e-405e14ffc013.png">

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
確認ありがとうございます。
[dbe14f8](https://github.com/coias/coias-front-app/commit/dbe14f8e68f7d8059b8d85ef3f7289b21245530f)
にて修正しました。確認お願い致します。

**Comment by COIAS-program** [comment]
ご対応いただきありがとうございました。
画面も無事に切り替わりました。
issueをクローズさせていただきます。
