### ISSUE TITLE
それぞれのボタンはどのスクリプトに対応しているのでしょうか?

### ISSUE THREAD

**Issue by AnbaiAnbai** [aizulab/coias-front-app#30]
https://github.com/aizulab/coias-front-app/blob/e36a77a78234e8588e3ac6936eda3a936ce64fea/src/page/ExplorePrepare.jsx#L21-L30

@COIAS-program 
これがそれぞれのボタンに割り振られているスクリプトになります。
このqueryが、localhost:8000/の後ろにボタンが押されるたびに連結しリクエストされ、そのレスポンスとしてスクリプトの処理結果が返却されます。（{ id: 2, name: '事前処理', query: 'preprocess' }の場合、事前処理が押されると、localhost:8000/preprocessにリクエストを送信します）

localhost:8000でのスクリプトは、https://github.com/aizulab/COIAS_program_github/blob/main/API/main.py　
にてqueryごとにそれぞれ処理をしています。ご確認をお願い致します。

**Comment by Mizunanari** [comment]
sugiura keisuke

現状では「ビニングマスク」ボタンと「光源検出」ボタンが分かれており、「光源検出」ボタンが後に来ていますが、
実は「ビニングマスク」ボタンで呼び出されているstartsearch2Rスクリプトで光源検出が同時に行われています。
個人的にはビニングマスクと光源検出を分ける必要もないと思いますので、
ビニングマスクボタンの名称を「ビニングマスク・光源検出」に変更し、光源検出ボタンを消してしまうのが一番簡単なお手当かと思いますが、
いかがでしょうか?

Seitaro Urakawa

コメントの通り光源検出はstartsearch2Rの中で行われているので「ビニングマスク・光源検出」に変更。光源検出ボタンは削除で良いと思います。

**Comment by urakawa-seitaro** [comment]
はい、メールの通り。その光源検出ボタン削除でお願いします。

**Comment by Mizunanari** [comment]
#29 に移行
