### ISSUE TITLE
グラブとズームがうまくいっていないかも

### ISSUE THREAD

**Issue by AnbaiAnbai** [aizulab/coias-front-app#32]
ブラウザはSafariで実行しているのですが、添付のスクショのようにグラブやズームをすると、初期の描画領域だけに画像があり移動したりズームしたりして新たに現れた領域は灰色のままになっています。
ブラウザをChromeにしたら良いかもしれません。

**Comment by Mizunanari** [comment]
探索モードの惑星選択画面は実装途中のため、今後も変更されます。
変更後に再度確認をお願いできますでしょうか？

**Comment by COIAS-program** [comment]
すみません、確認が遅くなりました。
再測定モード実装後とのこと、承知いたしました。

**Comment by Mizunanari** [comment]
何度か変更を加えました。
バグと呼べる程ではないことから、#46 に移行させていただきます。
今後、グラブ・ズーム・スクロールに関するご意見はこちらにお願いできますでしょうか。
