### ISSUE TITLE
二回目以降の探索準備をした時のバグ

### ISSUE THREAD

**Issue by AnbaiAnbai** [aizulab/coias-front-app#36]
探索準備モードを実行した後、探索/再描画を実行し、そのまま探索準備モードに戻って別の画像を選んで解析を行い、もう一度探索/再描画モードを実行したところ、枠と画像が合っていませんでした。
見た感じ、枠の位置は2回目の解析で得られた位置になっていましたが、画像は1回目の解析で得られたものがそのまま使用されているようでした。(作業ディレクトリの中身を直接確認できないので間違っているかもですが)
データの混合を避けるため、画像を読み込む際は直前に作業ディレクトリ(fits画像や中間ファイルが置かれるディレクトリ)は毎回空にした方が良いかと思います。

**Comment by COIAS-program** [comment]
仕様変更をされたようで、新しいfitsファイルをアップロードするたびに新しい整数番ディレクトリを作成してその中で解析を行うようになっているようですね。
また画像も最新の整数番ディレクトリ内のpngファイルをtmp_imagesにコピーして使用しているようですので、これも最新のデータと整合的になっていると思います。

ただブラウザのキャッシュに画像が残っていてそれを使用してしまう可能性はある(素人なので否定できない)ので注意はしておいた方がいいかもしれません。

4月7日追記
先ほども探索準備->探索/再描画と進んだのち、コンテナ内のターミナルでtmp_filesとtmp_imagesの中身を全てrmで削除したのちに、別のデータを探索準備->探索/再描画と進んだら前のデータの画像が表示されているようです。
ブラウザのURL欄を叩いて再表示させたら正しい画像が表示されました。
どうもブラウザをリフレッシュしないまま探索/再描画->探索準備->(再び)探索/再描画と進むと、前回の画像をそのまま表示してしまうようです。
なんでそうなるのかはよくわからないのですが、キャッシュに画像が残っているのが原因でしょうか?
キャッシュの強制クリアなどはできないでしょうか?

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
たくさんのご意見ありがとうございます。

こちらのissueについて、cacheを残らないようにすることで、[efb08cb](https://github.com/coias/coias-front-app/commit/efb08cb5d576c4c6082defa9df152c8c123fbc77)にて修正させて頂きました。
現在chrome,safari,firefoxにて正常な動作を確認いたしました。

ご確認と、問題がなければ、 #41 とともにcloseをよろしくお願い致します。

**Comment by COIAS-program** [comment]
一回目の探索/再描画モードを経由して二回目に探索モードに入った時も、正しく二回目の画像と枠が表示されることを確認致しました。
ご対応いただきありがとうございます。
close致します。
