### ISSUE TITLE
ファイルの入力制御

### ISSUE THREAD

**Issue by Mizunanari** [aizulab/coias-front-app#38]
Sugiura Keisuke

前提: fitsファイル名の書式
warp-HSC-[1文字か2文字のバンド名]-[領域を示す番号]-[サブ領域を示す番号1],[サブ領域を示す番号2]-[時刻].fits
例: warp-HSC-R2-0-1,4-122590.fits
- ファイルの数が5個以外の場合 (今後5個以外も対応する可能性はありますが、現状は5個にしか対応していないので、5個で固定して良いと思います)
- ファイルの拡張子が全て.fitsではない場合
- 5個のファイルの観測領域が全て同じではない場合。この判断はファイル名の (例で言う所の) -0-1,4- が同じであれば同じ領域となるので、これが異なるファイルが混じっていたらアウト
上記3点の場合はエラーを出して再入力させるようにしていただけますと幸いです。

**Comment by COIAS-program** [comment]
4月7日追記
書式について正しくは
warp-HSC-[1文字か2文字のバンド名]-[領域を示す番号(1-4桁くらい)]-[サブ領域を示す番号1],[サブ領域を示す番号2]-[時刻].fits
2つ目の[]の領域を示す番号は1桁とは限らず、少なくとも4桁の例もありました。

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
[aee2046](https://github.com/coias/coias-front-app/commit/aee2046da7ebba3e0385ed2505a2d42fe3604bfd)
にて、エラーを左下のポップアップで出すように修正致しました。
エラーの種類は、以下の三つを用意しました。

  1. ファイル名の形式が違います
  2. 観測領域が異なります
  3. 5枚の画像を入力してください

ご確認お願い致します。

**Comment by COIAS-program** [comment]
ご対応いただきありがとうございます。
完璧だと思います。
