### ISSUE TITLE
チェックボックスと枠のクリックが同期しない場合がある

### ISSUE THREAD

**Issue by Mizunanari** [aizulab/coias-front-app#39]
Sugiura Keisuke

>karifugo_disp.txtかnumbered_disp.txtに記載の天体でもチェック(=四角をクリックするか右のチェックボックスにチェックを入れ、四角の色を変えてチェックを入れる)できてしまう例がまだあると思いますので、unknown_disp.txtに記載の天体のみしかチェックできないようにご確認をお願いします。(こちらはもしかしたら間違っているかもしれません)
右のチェックボックスでチェックできないようになっている天体でも、その天体の四角をクリックすると色が変わり右のチェックボックスにもチェックが入ってしまうようになっているので、整合的な反応になるようにご対応をお願い致します。(こちらは確実です、修正をお願い致します)

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
[3a92a31](https://github.com/coias/coias-front-app/commit/3a92a314843f3010989c3ea3d5a32820261a2f2c)
によって修正させて頂きました。ご確認をお願い致します。

**Comment by COIAS-program** [comment]
現状確認できる範囲において、既知天体はクリックもチェックもできないこと、未知天体はクリックチェック赤枠が整合的になっていることを確認いたしました。
ただしnumbered_disp.txtに記載の確定番号付き既知天体はクリックできるようになってしまっていますが、同様の内容がissue #40 でオープンのままになっているので、そちらでご対応いただければと思います。

こちらのissueはクローズで良いと思います。
ただバックエンド側にバグがあり探索モードにおいてunknown_disp.txtしか表示していない動作になっているため、細かいことはまた再度確認させていただきます。
