### ISSUE TITLE
再描画時の既知天体の表示について

### ISSUE THREAD

**Issue by Mizunanari** [aizulab/coias-front-app#40]
Sugiura Keisuke

>探索モードでは既知天体の四角が表示されないが、再描画モードでは表示されることがある。
添付ファイルが一例ですが、1探索モード.jpgでは四角が表示されていない真ん中よりの天体が、2再描画モード.jpgでは四角が表示されています。

![1探索モード](https://user-images.githubusercontent.com/54758260/162346906-b90657a7-b253-4722-ac35-808b35b20faf.jpg)

![2再描画モード](https://user-images.githubusercontent.com/54758260/162346889-39e80176-cdbb-4747-83f8-5dc15669f399.jpg)

**Comment by Mizunanari** [comment]
@urakawa-seitaro @COIAS-program 

動作として正しいのはどちらでしょうか？

1. 既知天体の枠は常に表示される
2. 既知天体の枠は再描画前に表示され、再描画後に消える

**Comment by COIAS-program** [comment]
@Mizunanari @urakawa-seitaro 
既知天体(=numbered_disp.txtに記載の確定番号天体とkarihugo_disp.txtに記載の仮符号天体)の枠は、常に(=探索モードでも再描画モードでも再測定モードでも)黒色で表示されるが、ただし選択(=四角をクリックしても右側のチェックボックスをクリックしても)は不可能、が正しい実装だと思います。

**Comment by Mizunanari** [comment]
@COIAS-program 
承知しました。ご回答ありがとうございます。

**Comment by Mizunanari** [comment]
@COIAS-program 
以前、表示する小惑星をdisp.txtからunknown_disp.txtに変更いたしました。
unknown_disp.txtに出力される枠が未知の小惑星でこちらを表示するとのことだっと思います。
既知天体を表示するとした場合、既知天体のみ座標などが必要になるのですがファイルに書き出しなどをおこなっていますでしょうか？
確認お願いします。

**Comment by COIAS-program** [comment]
@Mizunanari 
ご連絡ありがとうございます。
既知天体のうち確定番号ありの天体の座標はnumbered_disp.txtに、仮符号番号の天体の座標はkarifugo_disp.txtに書き出してあります。
両方ともに記載してある座標に枠の表示が必要です(ただし常に黒枠、クリックすることもチェックボックスをチェックすることもできず赤枠にはならない)。
ご確認よろしくお願い致します。

4月11日現在
なお、現在バグによってnumbered_disp.txtが空になる不具合が起きています。
バックエンド側で応急処置はしたのですがデバッグがまだですので、coiasプロジェクトへの反映はしばらくお待ちください。
numbered_disp.txtの一例をここに貼っておきます。
[numbered_disp.txt](https://github.com/coias/coias-front-app/files/8460723/numbered_disp.txt)

4月12日現在
numbered_disp.txtは正しく表示されるようになりました。(バックエンド側の改修とastroqueryの改善によって)
coias / coias-back-app /以下のスクリプトにも反映してありますので、最新版ならnumbered_disp.txtも正しく表示されるはずです。
こちらでデバッグなどを行っていただければと思います。

**Comment by urakawa-seitaro** [comment]
> 4月12日現在
> numbered_disp.txtは正しく表示されるようになりました。(バックエンド側の改修とastroqueryの改善によって)
> coias / coias-back-app /以下のスクリプトにも反映してありますので、最新版ならnumbered_disp.txtも正しく表示されるはずです。

一旦古いバージョンは削除して、4月14日版で再インストールして実行してみました（進捗に驚きました。すごく使いやすくなっている。）
ここでのissue.探索モードで「確定番号」「仮符号番号」の天体が表示されない。
再描画だと表示される。
という状況に変化がなかったのですが、いかがでしょう。確認いただければと思います。

**Comment by COIAS-program** [comment]
@urakawa-seitaro 
こちらのissueの状態はまだオープンのままですので、ご対応いただいている途中だと思います。
ちなみに、直上のClosedは、僕がクローズされたissueからmentionをしたことを示しているだけで、このissueがクローズされた訳ではありません。

**Comment by Mizunanari** [comment]
@COIAS-program 

対応ありがとうございます。
再度確認させてください。

|テキストファイル|詳細|
| -- | -- |
| disp.txt | 既知小惑星と未知小惑星が記載 |
| unknown_disp.txt | 未知小惑星が記載 |
| karifugo_disp.txt | 既知小惑星のうち仮符号小惑星が記載 |
| numbered_disp | 既知小惑星のうち確定番号小惑星が記載 |

現在、探索モードではuknown_disp.txtを参照しています。
既知天体を表示（色付き？、枠選択不可）するには、既知天体のみのデータが必要になります。
２通りの方法が思いつきます。

1. karifugo_disp.txt + numbered_disp.txt = 既知天体のみのデータ
2. disp.txt - unknown_disp.txt (差分を表示する)

簡単なのは1の方法ですが、間違いありませんか？

**Comment by COIAS-program** [comment]
@Mizunanari 
ご確認をいただきありがとうございます。
はい、1の方法で間違いないと思います。(ファイルがいっぱいあってややこしくて申し訳ないです。。。)
disp.txt = numbered_disp.txt (番号付き既知天体) + karifugo.txt (仮符号既知天体) + unknown_disp.txt (未知天体)

既知天体は黒枠のまま選択不可で良いと思います。(original COIASでもそうしているので)
なので、
既知天体 = numbered_disp.txt + karifugo_disp.txt は黒枠のまま選択不可
未知天体 = unknown_disp.txt は選択可能
となるかと思います。

お手数ですが、どうぞよろしくお願い致します。

**Comment by COIAS-program** [comment]
ちなみに、original COIASではdisp.txtのみを見て、天体名が5文字(=番号付き既知天体)であるかKで始まる(≒仮符号既知天体)場合には選択不可にする、という方法を取っておりました。
が、今後表示名を変えたいなと個人的に思っておりますので、この方法は問題があります。
なので、薄さんがおっしゃるようにファイルの中身で区別するのが確実です。
表示天体名が変わろうが、numbered_disp.txtとkarifugo_disp.txtの中身は既知天体、unknown_disp.txtの中身は未知天体ですので。

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
返信ありがとうございます。
[364b846](https://github.com/coias/coias-front-app/commit/364b846571b62370b16d5b0d39e15e74f20ff21b)にて修正させて頂きましたので、ご確認をお願い致します

**Comment by COIAS-program** [comment]
@AnbaiAnbai @Mizunanari 
ご対応いただきありがとうございます。
karifugo_disp.txtとnumbered_disp.txtにデータが入っているときに正しく表示されることを確認致しました。

ただ、仮符号天体か確定番号天体が視野内に1つも検出されないとき、karifugo_disp.txtかnumbered_disp.txtは空になります。
このとき、空のファイルを読み込めずに以下のfile not foundエラーを出してしまい、探索/再描画の画面でGUI画面が止まってしまいます。
INFO:     172.18.0.1:64562 - "GET /karifugo_disp HTTP/1.1" 404 Not Found

unknown_disp.txtが空になることは恐らくないのですが、karifugo_disp.txtもしくはnumbered_disp.txtは空になることがあり得ますので、この場合でもうまくいくようにご対応をお願い致します。

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
ご確認とご報告ありがとうございます。
[3f12268](https://github.com/coias/coias-front-app/commit/3f1226825eb6f375a728183d51bd9fc72b3f4814)にてkarifugo_disp.txtとnumbered_disp.txtの両方のファイルが空だった場合にそのまま実行させるように修正しました。
ご確認をお願い致します。

**Comment by COIAS-program** [comment]
@AnbaiAnbai 
ご対応ありがとうございます。
karifugo_disp.txtが空の状態、ただしnumbered_disp.txtには確定番号既知天体の座標が書いてある状態でテストを行ったのですが、描画はできました。
ただし、numbered_disp.txtに記載の確定番号既知天体が探索モードにて再び描画されなくなりました。。。

ログを見る感じ、unknown_dispを呼んだあとkarifugo_dispを呼ぼうとして失敗してそこで処理が止まり、numbered_dispが呼ばれていないように見えるのですが、どうでしょうか?
あるいは、ソースコードを上書きして昔の状態に戻っていませんか？
ご確認をお願い致します。
![スクリーンショット 2022-04-21 12 42 23](https://user-images.githubusercontent.com/86390904/164367605-ec8452dd-cc06-405b-ae00-46f581dd78b5.png)

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
何度も申し訳ございません。
確認し、修正したのですが、描画後、再描画が表示されないバグが新たに発見したのでそちらを優先的に解決します。
もしかすると自分の環境だけでのエラーかもしれませんので、確認をお願いしてもよろしいでしょうか。

追記：すみません恐らく自分の環境だけのエラーでした。

**Comment by COIAS-program** [comment]
@AnbaiAnbai 
再描画が表示されない現象は私の環境では出ないですね。。。

描画/再描画時に(例え空であったとしても)karifugo_disp.txtとnumbered_disp.txtが表示されていることを確認致しました。
これでこのissueは解決で良いかと思いますので、closeさせていただきます。
ご対応いただきありがとうございました。
