### ISSUE TITLE
探索/再描画->探索準備->探索/再描画の時、画像の描画が行われない

### ISSUE THREAD

**Issue by AnbaiAnbai** [aizulab/coias-front-app#41]
https://github.com/coias/coias-front-app/blob/0222470e9938d712d68cf52a8610c66b2a6d82b2/src/component/PanZoom.jsx#L130

に何かを追加するorそもそものaxiosではなく、useSWR等に変える

**Comment by AnbaiAnbai** [comment]
[533206a](https://github.com/coias/coias-front-app/commit/533206a27a58c13a184f1bf2a122a4e68f4a8b32)
にて修正

**Comment by COIAS-program** [comment]
すみません、一度クローズしていただいたこちらのissueですが、私の環境ではやはりうまくいっていないので再度オープンさせていただきます。
ちなみに、探索準備 -> 探索モード -> 再描画モードまで進んだ後に、改めて探索準備モードに戻り違う画像をアップロードし、再度探索準備 -> 探索モードと進むと、枠の位置と画像の両方ともが1度目の再描画モードと同じものが表示されます。(つまり、2度目の探索準備モードの枠が全く反映されていない)
この場合も、上のURL欄を叩いてリフレッシュすると正しく表示されます。

環境やブラウザに依存しそうなバグなので厄介そうですが、よろしくお願い致します。

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
恐れ入ります。紛らわしくて申し訳ないのですが、こちらのissueは、自分が新たに見つけたバグでして、

> つまり、2度目の探索準備モードの枠が全く反映されていない)

こちらのバグに関してましては、issue #36 にて修正させて頂きます。
よろしくお願い致します。

**Comment by COIAS-program** [comment]
別のバグだったのですね、、、
失礼いたしました。
#36 も解決していることを確認致しましたので、close致します。
