### ISSUE TITLE
再描画モードでの選択の仕様について

### ISSUE THREAD

**Issue by COIAS-program** [aizulab/coias-front-app#42]
優先度は非常に低いのでそのうちご対応いただければ大丈夫です。

再描画モード(添付写真)にて、全ての天体を選択できないようにしていただきたいです。(枠をクリックしても右側のチェックボックスをクリックしても、選択できない。枠も赤くならないしチェックボックスにチェックも入らない)
このモードではユーザーは目視で選択結果が正しいか確認し、気に入らなければ「やり直す」をクリックしてやり直す、気に入れば「探索終了」をクリックして終了するか判断するだけで、特段の処理は必要なさそうです。
4月13日に浦川さんと相談して決めた仕様ですので、忘れないようにメモ書き程度にここに書いておきます。
<img width="1393" alt="スクリーンショット 2022-04-14 19 05 01" src="https://user-images.githubusercontent.com/86390904/163363257-dc0156cc-077b-4679-99eb-9bf7a2b6bab4.png">
、

**Comment by AnbaiAnbai** [comment]
@COIAS-program @urakawa-seitaro 
https://github.com/coias/coias-front-app/commit/a6e3ad1d671b271b58aaf506323fe1dbd830b4ea
にて修正させて頂きました。
ご確認をお願い致します。

**Comment by COIAS-program** [comment]
確認致しました。
ご対応いただきありがとうございます。
