### ISSUE TITLE
探索終了ボタンを押すと画面が真っ白になり操作を受け付けなくなる。

### ISSUE THREAD

**Issue by urakawa-seitaro** [aizulab/coias-front-app#43]
探索終了ボタンを押すと一瞬レポート作成画面（OBSやMEAを記入する画面）が表示されたのち、画面が真っ白になりました。

**Comment by urakawa-seitaro** [comment]
解像度落としてますがこんな感じです。
https://user-images.githubusercontent.com/65066368/163386489-8f240224-6ad4-4b27-91e7-a3428bb9bc5b.mov

**Comment by AnbaiAnbai** [comment]
@urakawa-seitaro 
ご確認ありがとうございます。
私のchrome環境において、こちらのバグが発生しなかったため、お手数ですがエラーログを確認させて頂きたいです。

ログの確認方法は、chrome環境での手順だと、真っ白になったタイミングでブラウザ上にて右クリック→検証をクリック→コンソールログ表示となります。こちらをスクリーンショットで送っていただけますでしょうか。

<img width="1436" alt="inspect" src="https://user-images.githubusercontent.com/97570265/163509356-cacef4b9-5227-4fda-938e-95a80a38d353.png">

**Comment by urakawa-seitaro** [comment]
開発環境がうまく動かなくて、一般ユーザーな環境(VScodeなし)で実施しました。今一度開発環境構築して実行してみます。

**Comment by COIAS-program** [comment]
私も、浦川さんの動画のように探索モード -> 再描画モード -> 探索終了を押してレポートモードに移行したときはこの現象は起きませんね。。。
ただし、探索モードから直接(再描画モードを経由せずに)探索終了が押せるようになっており、探索モードから直接探索終了を押してレポートモードに移動すると同様に一瞬レポート画面が見えた後に真っ白になります。
とはいえ、これは探索モードで再描画を押した時に処理をいくつかしていてレポートモードに必要な新しい中間ファイルができるのですが、再描画を押さなければそれらができないので当然ではありますが。。。
何かの参考になりましたら幸いです。

**Comment by AnbaiAnbai** [comment]
ご指摘ありがとうございました。

@urakawa-seitaro 
> 開発環境がうまく動かなくて、一般ユーザーな環境(VScodeなし)で実施しました。今一度開発環境構築して実行してみます。

ご対応ありがとうございます。現在こちらのGitHubにある物が最新版となりますので、そちらで一度確認していただけると幸いです。

@COIAS-program 
> ただし、探索モードから直接(再描画モードを経由せずに)探索終了が押せるようになっており、探索モードから直接探索終了を押してレポートモードに移動すると同様に一瞬レポート画面が見えた後に真っ白になります。

こちらのご指摘に関しまして、再描画に入らなければ、探索終了ボタンを押せない仕様に変更させて頂きました。
ありがとうございました。

**Comment by AnbaiAnbai** [comment]
@urakawa-seitaro @COIAS-program 
ご報告いただいたバグに関しまして修正を私の環境ですが確認しましたので、こちらはcloseさせて頂きます。
また何かバグがありましたら、お手数ですが再度openまたは、issueとして新しくお願い致します。

**Comment by urakawa-seitaro** [comment]
すいません。再openしました。開発環境下で確認しました。

<img width="1014" alt="スクリーンショット 2022-04-29 18 03 40" src="https://user-images.githubusercontent.com/65066368/165915566-21f1363a-8436-49c0-9af0-856cfdc135f7.png">

chromeのコンソール画面は上記のようでした。

**Comment by urakawa-seitaro** [comment]
あと、Vscodeでのエラーは以下のとおりです。バックエンド側の軌道チェックプログラム（AstsearchR_afterRecoias）でエラーをだしていました。
<img width="674" alt="スクリーンショット 2022-04-29 17 51 30" src="https://user-images.githubusercontent.com/65066368/165915934-4a4220c2-ed55-4a40-98f4-4239f501d615.png">

**Comment by COIAS-program** [comment]
@urakawa-seitaro 
バックエンド側の問題の可能性が高いですね。
問題を起こした時のresult.txtを見られますか?
あと私の方でも確認したいので、問題を起こした時の5枚のwarpファイルをいただきたいです。
可能なら、どの天体を選択したかのリストも確認できますと幸いです。

あるいは、月曜日にzoomをする時に直接見せていただく方が早いかもしれません。

**Comment by urakawa-seitaro** [comment]
月曜のzoomで確認しましょう。
