### ISSUE TITLE
探索モードで探索終了ボタンを押せないようにする/探索終了ボタンを消す

### ISSUE THREAD

**Issue by COIAS-program** [aizulab/coias-front-app#44]
現在、探索モードにて直接探索終了ボタンが押せるようになっていますが、処理の関係で必ず再描画モードを経由しなければいけません。
そのため、探索モードでは天体を選択後必ず再描画モードに行くようにするため、探索終了ボタンを押せないようにするか、探索モードで探索終了ボタンを消してしまうのが良いと思います。
個人的には、消してしまった方がすっきりして良いかなと思います。
ただし、再描画モードでは「やり直す」ボタンと「探索終了」ボタンが必要ですので、こちらのモードからは消さないようにお願い致します。

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
ご意見ありがとうございます。
[66a4d94](https://github.com/coias/coias-front-app/commit/66a4d9425aced2b5794d9cdca77db806ddd93b46)にて対応させて頂きましたので、ご確認お願い致します。

**Comment by COIAS-program** [comment]
確認致しました。
ご対応いただきありがとうございます。
