### ISSUE TITLE
ブリンク機能の初期化について

### ISSUE THREAD

**Issue by COIAS-program** [aizulab/coias-front-app#45]
探索モード/再描画モードにてブリンクを止めないまま、(レポートモードを経由してもしなくても)探索準備モードに戻り、再度探索モードに入ると、ブリンクが起動したままになります。
しかもこの場合、内部変数とボタンの状態が一致していないためだと思われますが、ブリンクボタン(右矢印/四角)を押してもブリンクを止められなくなります。
探索/再描画の画面に入り直すたびにボタンの状態を初期化すれば良いのではないでしょうか?
お手数ですが、ご対応をお願い致します。

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
ご指摘ありがとうございます。
[318f998](https://github.com/coias/coias-front-app/commit/318f998f7b4327ac86803c69ed0cc6737889d1f6)にて修正させて頂きましたので、確認をお願い致します。

**Comment by COIAS-program** [comment]
こちらも確認致しました。
ご対応いただきありがとうございます。
