### ISSUE TITLE
移動天体候補四角マークのON/OFF機能の実装

### ISSUE THREAD

**Issue by AnbaiAnbai** [aizulab/coias-front-app#48]

**Comment by COIAS-program** [comment]
探索モード・再描画モードにて天体の四角と名前がON/OFFできることを確認致しました。

ただ、まだ再測定(手動測定)モードが実装途中なので仕方ないのですが、このモードでもON/OFFが切り替えられるようにしていただきたいです。
実は四角の影に隠れて検出されていない光源が見えないことがあるので、むしろ再測定(手動測定)モードの方に四角・名前のON/OFF機能がクリティカルだったりします。

そのため、まだこのissueは開いたままにさせていただきます。

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
ありがとうございます。
コミット：[85a4a3e](https://github.com/coias/coias-front-app/commit/85a4a3e12c8527e4ac99870e357c407eee825344)
ブランチ：anbai-update-manualmode
にて、同時に再測定にon/offを実装させていただきました。

ご確認をお願い致します。

**Comment by COIAS-program** [comment]
再測定(手動測定)モードにて四角のon/offが実装されていることを確認致しました。
mainブランチにマージしていただければと思います。
このissueはクローズさせていただきます。
