### ISSUE TITLE
prempedit3.pyに渡す引数を入力可能にする

### ISSUE THREAD

**Issue by Mizunanari** [aizulab/coias-front-app#5]
prempedit3.pyに渡す引数をフロントアプリから入力可能にする

**Comment by Mizunanari** [comment]
> 新天体番号は指定なしで良いと言いましたが、やはり指定があった方が良いです（申し訳ない）。理由は、ユーザーが複数のエリア（例えばエリア1、エリア2）を探索するとき、エリア2で見つけた天体のHで始まる番号はエリア1で見つけた天体のH番号の連番である方がユーザにとっても取りまとめる私にとってもわかりやすいからです。

https://coiashq.slack.com/archives/C034Z0GDEBX/p1648652573604459

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
再描画時に確認画面が出る機能にて、修正させて頂きましたので、確認をお願い致します。

**Comment by COIAS-program** [comment]
@AnbaiAnbai 
確認致しました。
ダイアログの説明、数値が負だったり文字が含まれていたり100万番を超えていたりした場合に弾く機能など搭載していただいていて、完璧だと思います。

ただ、再描画画面で「やり直す」ボタンを押しても反応しなくなっているようです。
ご確認いただけますでしょうか?

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
確認ありがとうございます。打ち合わせお疲れ様でした。
こちらのバグについて修正しましたので、確認をお願い致します。

**Comment by COIAS-program** [comment]
@AnbaiAnbai 
こちらこそ、打ち合わせありがとうございました。
やり直すボタンが押せるようになっていることを確認致しました。

ただ以下のバグがありましたので、ご確認をお願い致します。
探索モードで天体を選択 -> 「探索終了」を押して最初の新天体の番号を打ち込む -> 再描画モードにて「やり直す」を押す -> 再度探索モードで天体を選択し「探索終了」を押す、のフローで進んだ時、新天体の番号を指定するダイアログで新天体の番号を指定せずに「次へ」を押しても1回目に打ち込んだ番号からの連番になる。
前回の履歴を引きずっていると思いますので、初期化をお願いします。
またこのフローで進んだ時、新天体の番号を指定するダイアログで「指定する」のチェックが入っているときに番号指定ができずに、逆にチェックが外れているときに指定が可能となっている。
これも前回の履歴を引きずっているのに画面の表示だけもとに戻っているので、内部変数と表示が合っていないのだと思います。

ご確認をお願い致します。

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
度々のバグ発生申し訳ございませんでした。
二つのバグについて初期化する方法で[fcaa2b9](https://github.com/coias/coias-front-app/commit/fcaa2b9c1b20daa80024a32a3b57b54a7ef0f689)にて修正させて頂きましたので、確認をお願い致します。

**Comment by COIAS-program** [comment]
@AnbaiAnbai 
ご対応いただきありがとうございます。
探索モードと再描画モードを行ったり来たりしてもダイアログで指定する新天体の初期番号とチェックボックスが正しく表示されていることを確認致しました。

ただ、ダイアログの右上のバツ印を押してダイアログを閉じたとき、ユーザーとしては入力をキャンセルして探索モードに戻る気持ちだと思うのですが、全ての天体にチェックが入った状態の再描画モードに入ります。
またこの後に「やり直す」ボタンを押して探索モードに戻り、もう一度ダイアログを開くと、チェックボックスと入力できる/できない状態が合わない状態になります。
ダイアログの外をクリックしてもダイアログが閉じられてしまい同様の症状が出ますね。。。

提案なのですが、ダイアログの右上のバツ印を消した上で、ダイアログ外をクリックしてもダイアログが閉じないようにして、「次へ」ボタンを押さなければ絶対にダイアログが閉じないようにしてはどうでしょうか?
その方がフローが明確になってバグ取りもしやすくなります。
再描画モードでも「やり直す」ボタンで自由に探索モードに戻れるので特に問題はないかと思います。

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
ご指摘ありがとうございます。
ご提案の通り、ダイアログのバツ印を消し、外をクリックしても消えない仕様に変更して対応させて頂きました。

ご確認お願い致します。

**Comment by COIAS-program** [comment]
@AnbaiAnbai 
ご対応いただきありがとうございます。
色々試してみましたが、これでこのissueに関しては完璧で特に問題はないようです。
issueを閉じさせていただきます。
