### ISSUE TITLE
再測定（手動測定）モードのアパーチャを長方形にする

### ISSUE THREAD

**Issue by AnbaiAnbai** [aizulab/coias-front-app#51]
@urakawa-seitaro @COIAS-program 
#1 の中のさらに細かい部分での実装となりますが、長方形にする際の基準について

クリックした

- １〜２点目の長さが横
- ２〜３点目の長さが縦
- 長方形自体の傾きは、１〜２点目の角度を傾きとする

となり、最終的に出力するのに必要なのは、

1.　選んだ3点の座標
2.  １点目から3点目（対角線）の中心の座標

という認識です。

認識が合っているか、もしくは、足りない部分がありましたら
このissueにて、返信をよろしくお願い致します。

**Comment by COIAS-program** [comment]
四角の厳密な作り方はこちらの関数をご覧ください。
https://github.com/COIAS-program/COIAS_program_github/blob/main/COIASlibs/calcrect.py
入力のr1, r2, r3がそれぞれ1, 2, 3点目の[x, y]座標を持つ要素2のリストです。
ここから計算されるrectPos1 - 4が四角形の頂点の座標になります。
GUIで確認する四角形とバックエンド側の測光時に生成する四角形がずれると大変なので、厳密に合わせるようにお願い致します。

現状のバックエンド側で書き出している4点は、拡大前の画面でクリックした1点と、拡大後の画面で長方形を作るべく選んだ3点の座標です。
が、確かに拡大前の画面でクリックした点は精度が悪いので、代わりに対角線中心の座標を出した方がいいかなと思いました。
なので、ここはバックエンド側が合わせるように致します。
ただし、書き出すmemo_manual.txt の書式は添付のファイルに合わせるようにお願い致します。
スペース区切りで
Hを除いた天体番号(disp.txtに記載のH番号+1より大きい番号) 画像番号 対角線の中心座標x y 長方形を作るべく選んだ3点のx y(3組)
[memo_manual.txt](https://github.com/coias/coias-front-app/files/8852086/memo_manual.txt)

**Comment by COIAS-program** [comment]
あと細かいのですが、GUI上では画像の番号を1から始めていますが、バックエンド側での解析ではPythonのリストの添字法則に従い0から始めています。

**Comment by AnbaiAnbai** [comment]
@COIAS-program @urakawa-seitaro 
コミット：[85a4a3e](https://github.com/coias/coias-front-app/commit/85a4a3e12c8527e4ac99870e357c407eee825344)
ブランチ：anbai-update-manualmode
にて、修正させていただきました。

ご確認をお願い致します。
