### ISSUE TITLE
再測定モードで、探索/再描画のように、今何枚目にいるのかをわかるようにする

### ISSUE THREAD

**Issue by AnbaiAnbai** [aizulab/coias-front-app#52]
探索/再描画のコンポーネントをそのまま持ってくることで解決する可能性がある

もしくは、再測定用にアレンジすることも考える

**Comment by AnbaiAnbai** [comment]
@COIAS-program @urakawa-seitaro 
コミット：[85a4a3e](https://github.com/coias/coias-front-app/commit/85a4a3e12c8527e4ac99870e357c407eee825344)
ブランチ：anbai-update-manualmode
にて、修正させていただきました。
ご確認をお願い致します。

**Comment by COIAS-program** [comment]
当該ブランチにて、再測定(手動測定)モードで今何枚目にいるかのコンポーネントが表示されていることを確認致しました。
この機能についてはmainにマージして良いと思います。
また、このissueを閉じさせていただきます。

ただし、https://github.com/coias/coias-front-app/issues/58 に書いております通り、画像の枚数が自由になったら現状のコンポーネントをそのまま使えないため、探索/再描画モードだけではなくこのモードも改修する必要があることをご承知おきください。
