### ISSUE TITLE
Grab,Zoom,Scrollの機能で、Grabの撤廃

### ISSUE THREAD

**Issue by AnbaiAnbai** [aizulab/coias-front-app#53]
三つの機能の共存は難しい、UI/UXの観点からも、あまりよくないため、
Grabの機能を撤廃し、ズームとスクロールの機能に絞る。

**Comment by hasegawa-taisei** [comment]
@urakawa-seitaro @COIAS-program 
グラブ機能を削除し、ズームとスクロール機能のみに変更いたしました。
ズーム機能は引き続きalt(option)ボタンを押しながら、マウスホイールを使用することでズームが可能です。
実際の動きは以下の動画のようになります。

こちらは新しく作成した`hasegawa-update-panzoom`のブランチで実装いたしました。
確認する際は、上部のブランチに移動していただき、実行をお願いいたします。

https://user-images.githubusercontent.com/105190797/172764658-eadf4700-c4ff-438d-a10f-4bf154daa828.mov

**Comment by COIAS-program** [comment]
グラブ機能が削除されていることを確認いたしました。
mainブランチにマージしていただいて良いかと思います。

個人的な意見ですが、コンフリクトが怖いので早めにマージした方が良いかと思います。
(またバグが見つかりましたらお知らせしますので)

ひとまず、このissueは閉じさせていただきます。
