### ISSUE TITLE
ズームインアウトに合わせて、天体の四角も拡大縮小

### ISSUE THREAD

**Issue by AnbaiAnbai** [aizulab/coias-front-app#54]
ズームインアウトによって、天体の名前と四角も拡大縮小させる。

デフォルトは今まで通りの大きさ、そこから、状況に応じて、拡大縮小をする。

**Comment by COIAS-program** [comment]
恐らく言葉だけではお伝えするのが難しい内容だったと思いますので、補足です。
現状では拡大すると四角まで大きくなってしまいますが、拡大時には四角の重なりがなるべく無くなって欲しいので、画面(画像の枠)と四角の比が一定になるようにするのが良いと思います。(つまり天体の四角と名前は見た目の大きさは変わらず、画像だけ拡大される)
一方で、縮小するときは全体を見渡すという目的ですので、画面枠と四角の比が一定にしてしまうと画像に対して四角の主張が大きくなり過ぎてしまうので、四角と名前は画像と一緒に小さくなった方が良いと思います。

**Comment by COIAS-program** [comment]
ズームに関するissueがこれしかないのでここに書かせていただきます。
現状のズーム機能ですが、ズームするにあたってスクロールバーの位置やサイズが正しく変化していることは確認致しました。
ただ、原点(画像の左上)を中心にズームをするようになってしまっています。
現在の画面の中央を中心にズームをするようにお願い致します。

**Comment by hasegawa-taisei** [comment]
@COIAS-program @urakawa-seitaro 
コミット : db7fc30
ブランチ : anbai-update-manualmode
上記にて実装致しました。
ご確認のほどよろしくお願いいたします。

**Comment by COIAS-program** [comment]
@hasegawa-taisei 
ご対応いただきありがとうございます。

1. 画像のボタンに「x10」などと書いてありますが、この数値は何を示しているのでしょうか? 単純に考えれば拡大率(=元画像の横方向の全ピクセル数/画像表示領域の横方向に表示されている部分の元画像でのピクセル数)になると思いますが、現状ではx10でもせいぜい4/3倍にしかなっていないように見えます。倍率の定義をしっかり定めた上で、表記と実際の拡大のされ方が合うようにお願い致します。

> 2. @urakawa-seitaro 上の定義をしっかり定めた上で、どの倍率を採用すべきかはまたきちんと考えなければいけないと思います。現状ではx1の次がx10になっており、この倍率が本当にある方向の拡大率ならば、x10だと画面10個分スクロールしなければ端までたどり着かないので、拡大しすぎな気がします。もう少し間が(x2とかx5?)あってもいいかもです。(1.の対応が優先)
表記ミスが原因。削除

3. 画面の中央を中心に拡大縮小するようになっていないので不便です。例えばx50で画像の右下を見ている時に、x200を押してさらに拡大するとあらぬ場所を見ていたりします。(完全にランダムな場所ではなく多少追随しているような気もしますが。。。前回の履歴を見ている?) 画面中央のpng座標を常に内部変数に記憶をしておき、拡大/縮小するときはその座標が中心に来るように拡大/縮小する、もしくは縮小する時に画面外が映るような場所にいる時は画面外が映らないように中心の座標をずらす、といった実装はできないでしょうか?

4. 天体の四角が小さすぎます。x1ならこの大きさで良いと思いますが、x50以上でこれは小さすぎます。ここら辺の調整は1.が固まってからだと思いますので、1.の修正後にお願いできればと思います。

**Comment by hasegawa-taisei** [comment]
@COIAS-program 
ご確認いただきありがとうございます。

1. 拡大率の表記に関しましてはこちらの実装の誤りでした。大変申し訳ございません。現在の拡大率は元画像の大きさを基準に1, 1.25, 1.5, 2, 3, 6倍の拡大率になっております。ボタンの表記はこの拡大率に合わせて修正させていただきます。

**Comment by COIAS-program** [comment]
@AnbaiAnbai @urakawa-seitaro 
承知致しました。修正よろしくお願い致します。

倍率の上限についてですが、もう少し大きくてもいいかなと思います。
png画像のピクセル数の最大値は把握している限りでは5100です。また明るめの天体の広がり方は10ピクセル程度です。なので10ピクセルがそれなりに解像できる拡大率が最大だと良いかと思います。
例えば20倍があれば、表示領域に横255ピクセル、縦125ピクセル程度入るように見えると思いますが、これなら10ピクセルの天体が程よく分解できるかと思います。

そこで、1, 1.25, 1.5, 2, 3, 6に加え、10と20も追加をお願いできますでしょうか?
ボタンが8種類になってしまいますが、元の画像サイズが500 ~ 5000の間で変わり得るので、ユーザーが色々と選べるようにしておいた方が良いかと思います。

**Comment by hasegawa-taisei** [comment]
@COIAS-program @urakawa-seitaro 
コミット : 16575ee
ブランチ : anbai-update-manualmode
上記にて実装致しました。

10,20倍の拡大率の追加。拡大に伴う四角の変化を、頂いた資料をもとに実装致しました。
デモ動画はサイズの問題により、slackの方に送らせていただきます。

ご確認のほどよろしくお願い致します。

**Comment by COIAS-program** [comment]
恐らく問題ないと思いますので閉めます。
