### ISSUE TITLE
探索準備モードで、バックエンドにいくつかのパラメータを渡せるように修正

### ISSUE THREAD

**Issue by AnbaiAnbai** [aizulab/coias-front-app#56]
- 自動測定の場合、全てデフォルトで実行。
- 手動測定の場合、パラメータを渡せるようにする。

上記の修正に伴って、デザインの修正から進める

**Comment by COIAS-program** [comment]
@urakawa-seitaro @AnbaiAnbai @hasegawa-taisei 
7/22時点仕様(今後の議論で変わるかもしれません)
設定したいパラメータは
1. nd (N Detection: 何枚以上で光源を検出したら移動天体と見なすか => 日本語: 検出光源必要数、デフォルト4)
2. ar (Aparture Radius: 自動測光での測光半径[pixel] => 日本語: 自動測光半径、デフォルト6)
3. sn (Source Number: 画像一枚あたりの光源数 => 日本語: 平均光源数、デフォルト2000)
の3つです。
それぞれ探索準備モードの最初の画面のどこかに設定できる窓をおいて、未入力ならデフォルト値を入れておいていただければと思います。(どれも慣れた人しか調整しないパラメータなので、目立つ場所におかなくて良いかも。現状の自動/手動解析の切り替えのように、「ファイル」ボタンを押したときに出てくるダイアログ内とかで設定できれば良いと思います)

1.と2.は自動検出 (astsearch_new) のスクリプトを叩くときに、 
astsearch_new nd=値 ar=値
の形でオプションのように与えます。
3. はビニングマスク (startsearch2R) のスクリプトを叩くときに
startsearch2R sn=値
のように同様に与えます。

**Comment by urakawa-seitaro** [comment]
arの値はビニング4*4を選択した時のデフォルト値を３に変更することは可能でしょうか？

**Comment by urichika** [comment]
@COIAS-program 
仕様についてのコメントありがとうございます。
front : urita-fix-parameter, back : main
で以下のように修正しましたので、確認お願いいたします。
![スクリーンショット 2022-08-02 14 54 07](https://user-images.githubusercontent.com/94360310/182302006-dac98d33-d2ca-4fdb-8f4d-1b96a56d0cc3.png)

**Comment by COIAS-program** [comment]
@urichika 
ご対応いただきありがとうございます。
仕様通り、設定したパラメータが渡されていることを確認致しました。
一点だけお願いなのですが、手動処理だけでなく全自動処理でもパラメータが設定できるようにしていただけないでしょうか?
全自動処理でもパラメータを設定したい場合があるので。

**Comment by urichika** [comment]
@COIAS-program 
ご意見ありがとうございます。
全自動処理でもパラメータを設定できるようにしましたので,確認お願いいたします。

**Comment by COIAS-program** [comment]
@urichika 
ご対応ありがとうございます。
全自動処理でも問題なくパラメータ設定できました。
mainブランチにマージしていただければと思います。
またこのissueを閉じさせていただきます。
