### ISSUE TITLE
vscodeで、react立ち上げ時のエラー

### ISSUE THREAD

**Issue by AnbaiAnbai** [aizulab/coias-front-app#57]
@urakawa-seitaro 
先ほど拝見した、vscodeで立ち上げるときに表示されるエラーについてなのですが、
原因はおそらく、vscode側の何らかのエラーと思われまして、こちらでもそのエラーを確認しました。

起動方法が他に二つございまして、そちらでは、エラー無く起動することを確認しました。

一つ目が、

1. **vscode起動後、画面上部のメニューバーから、**ターミナル**-->**新しいターミナル**で、ターミナルを新たに開く
2. ターミナルに、`yarn start` と打ち込む

二つ目が、

1. `command` + `shift` + `p` の三つのキーボードを押す
2. 出てきたウィンドウに、run task と打ち込む
3. yarn : start を選択

どちらも問題なく動くことを確認しましたが、もし何か不具合があれば、対応させていただきます。
確認よろしくお願い致します。

**Comment by urakawa-seitaro** [comment]
エラー出ずに起動できました。ありがとうございます。
