### ISSUE TITLE
使用する画像の枚数の自由化・フィルターの制限撤廃

### ISSUE THREAD

**Issue by COIAS-program** [aizulab/coias-front-app#58]
任意の枚数の画像を使用できるようにする方向になりそうですので、追加させていただきます。
バックエンド側のスクリプトに関してはすでに任意の枚数の解析に対応している(はず)です。
フロント側としてやっていただきたいアクションアイテムとしては、
・ファイルアップロード時の枚数制限を撤廃する
・探索モードなどで、5つの四角を用意しそれらを点灯することで現在の画像番号を表示していたのを、番号のみで示すようにする
あとはもしプログラムのどこかに「5」というマジックナンバーが入っている場合は、画像枚数に応じて可変になるようにお願い致します。

もう一点、ファイルアップロード時にフィルターが違っていても通すようにしていただきたいです。
ファイルの書式は、
warp-HSC-[filter]-[tract]-[patch]-[visit].fits
入力するファイル一式は [tract] と [patch] の値が一致してさえいればよく、filterは違っていても大丈夫です。
多分、現状ではfilterが違っていると弾かれるような設定になっているかと思いますので、よろしくお願い致します。

**Comment by hasegawa-taisei** [comment]
@COIAS-program
コミット : 86fc7bd
ブランチ：urita-fix-exploreprepare
上記にて実装いたしました。
枚数・フィルターの撤廃、またこれに伴に探索モードでの現在の画像番号の表示の修正を行いました。
ご確認の方よろしくお願い致します。

また、使用枚数の自由化についてですが、最低枚数はございますでしょうか。
現在は一枚でもファイルアップロードを行うことができ、その後の全自動または手動処理の際にエラーが出るようになっております。
最低枚数がございましたら、ファイルアップロード時にエラーハンドリングとしてモーダルの表示等をしたいと考えております。
よろしくお願い致します。

**Comment by COIAS-program** [comment]
@hasegawa-taisei 
ご対応ありがとうございます。
後ほど確認いたします。

最低枚数は3枚でお願い致します。
つまり、3枚は許容するが、2枚以下ならエラーを出して再度アップロードさせる(領域が異なる画像が混ざっていた時の挙動と同じ)動きでお願いしたく思います。

現状では、3枚の場合だとissue #56 にもあるパラメータを変えないと確定でエラーになるので、とりあえずそこは気にしなくても大丈夫です。
(バックエンド側でも3枚で試したことがないので他の箇所でもエラーが出る可能性はありますが、原理的には3枚でも可能なはずです)

**Comment by hasegawa-taisei** [comment]
@COIAS-program 
ご回答いただきありがとうございます。

コミット : a49324c

上記の最新コミットにて、最低枚数の設定とエラーの表示を実装いたしました。
こちらも合わせてご確認の方よろしくお願い致します。

**Comment by hasegawa-taisei** [comment]
@COIAS-program 
大変申し訳ございません。
コミット : a49324c　[#update :](https://github.com/coias/coias-front-app/commit/a49324c2ad140900db33e9fa2b83cc748e5e4b4b) https://github.com/coias/coias-front-app/issues/58 [最低枚数の設定、エラー表示](https://github.com/coias/coias-front-app/commit/a49324c2ad140900db33e9fa2b83cc748e5e4b4b)
上記コミットにて、ブリンクの箇所にバグがありましたので、以下のコミットで修正を行いました。

コミット : 8cb2de3
お手数をおかけいたしますが、こちらの最新コミットでご確認の方よろしくお願い致します。

**Comment by COIAS-program** [comment]
確認させていただきました。完璧だと思います。
15枚で解析することができました。UIも素晴らしいと思います。
また、
・領域が違う画像が含まれているときと、枚数が二枚以下のときに再アップロードを促すこと
・フィルターが違う画像が含まれていてもアップロードできること
も各人致しました。

特に問題ないと思いますので、mainブランチへのマージをお願い致します。
またissueもクローズいたします。
<img width="1388" alt="スクリーンショット 2022-07-22 11 25 24" src="https://user-images.githubusercontent.com/86390904/180359482-ab4b9578-e84d-4942-9d81-9da48a6b9ac8.png">
