### ISSUE TITLE
検出から逃れた点を自動検出ですでに検出された天体にappendする目的で、名前を変更するモードを実装する

### ISSUE THREAD

**Issue by AnbaiAnbai** [aizulab/coias-front-app#60]
自分で手動測定していて気がついたんですが、結構自動検出に漏れてるやつがいますね。
例えば、目で見れば明らかに5枚に移動天体として写ってるのに(既知含む)、自動検出では4枚しか検出されてないので、1枚だけ検出から逃れているのがよくあります。
手動測定モードで、その検出から逃れた点を自動検出ですでに検出された天体にappendする機能が必要かもしれません。
あるいは、自動検出で同一の点とみなす半径が厳しいのかもしれませんのでそこの検討も必要かもしれませんが、状況が異なる場合が多くパラメータの調整だけでは難しいと思うので、結局再測定(手動測定モード)で人力でなんとかするしかない印象です。

**Comment by COIAS-program** [comment]
モードについての詳細仕様を記したワードファイルを作成致しました。
[20220727名前付け替え機能詳細仕様.docx](https://github.com/coias/coias-front-app/files/9195686/20220727.docx)

**Comment by COIAS-program** [comment]
本日の確認では問題なかったので、ひとまずissueを閉じさせていただきます。
また気になることがあればslackでご連絡いたします。
