### ISSUE TITLE
キー入力でもブリンク・画像の移動をできるようにする機能(要望)

### ISSUE THREAD

**Issue by COIAS-program** [aizulab/coias-front-app#61]
使っていて思ったのですが、現在は(探索モードにせよ手動測定モードにせよ)天体の指定もクリックだしブリンクを開始/停止するのも画像を進める/戻すのもボタンクリックで行っています。
天体の探索はブリンクをしていないとできませんが、天体の移動が早い場合ブリンクを止めないと天体をクリックすることができないので、自然と作業がボタンクリックでブリンク開始 => 視認 => ボタンクリックでブリンク停止 => 天体クリック => ボタンクリックでブリンク開始 ... となり、マウスの移動が多くなり過ぎて煩雑に感じました。

そこで、例えばsキー(start/stop)を押した時もブリンクの開始/停止ができ、さらに右キーで次の画像に移動、左キーで前の画像に移動、とするのはどうでしょうか?
オリジナルCOIASに実装したら非常に快適になりました。

**Comment by hasegawa-taisei** [comment]
@COIAS-program @urakawa-seitaro 
コミット : 16f9e55
ブランチ：hasegawa-update-panzoom
上記にて実装いたしました。

確認の方よろしくお願い致します。

**Comment by COIAS-program** [comment]
hasegawa-update-panzoomブランチの探索/再描画モードでsキーによるブリンクの開始/停止と左右キーで画像を戻す/進めることができることを確かめました。

ただし、URLを叩いたりして探索/再描画モードに入った時には、画面にフォーカスが当たっていないせいかキー入力が受け付けられず、画面のどこかをクリックして初めてキー入力が可能になります。
この画面に入った瞬間にフォーカスを当てられないでしょうか?
また、中央の画像をクリックして画像にフォーカスを当てていると、左右キーで画像の位置が移動するだけになります。(しかもスクロールの外まで移動する)
画像にフォーカスが当たっている時にこの左右キーによる画像の平行移動を無効化できないでしょうか?

長谷川さんのブランチには再測定(手動測定)モードの機能は取り込まれていませんが、このsキーによるブリンクの開始/停止と左右キーによる画像戻し/送りは再測定(手動測定)モードでも実装していただきたいので、将来的によろしくお願い致します。

**Comment by hasegawa-taisei** [comment]
@COIAS-program @urakawa-seitaro
コミット : [b7ae675](https://github.com/coias/coias-front-app/commit/b7ae675bc64fafe1c632db5c0a7b44637023cd46)
ブランチ：hasegawa-update-panzoom
上記にて修正をいたしました。

画像上でのカーソルキーによるスクロールを無効化（画像上で「sキーによるブリンク、カーソルキーによる画像を進める、戻す」は可能になっております。）
ヘッダーから探索/再描画モードに入った場合と、探索/再描画モードに入った状態でページをリロードした後、どちらでも画面をクリックせずにキー入力でのブリンクが可能になるように変更いたしました。

ご確認のほどよろしくお願いいたします

**Comment by COIAS-program** [comment]
@hasegawa-taisei 
ご対応いただきありがとうございます。
お願いした点は完璧に実装されていますので、mainブランチへのマージをお願い致します。

先日書きましたように再測定(手動測定)モードにもこの機能を実装していただきたいので、このissueはまだ開いたままにさせていただきます。

**Comment by COIAS-program** [comment]
現在のmainを取り込んだanbai-update-manualmodeブランチにて、手動測定モードでキー入力が正しく動いていることを確認致しましたので、issuを閉じさせていただきます。
