### ISSUE TITLE
オートセーブ機能

### ISSUE THREAD

**Issue by COIAS-program** [aizulab/coias-front-app#62]
特に手動測定モードは注意深くアパーチャーを選んでいかなければいけないので、1組の画像全てを選び終わるのに30分とかかかったりします。
そういった作業の終盤に手で結果を出力(memo.txtとmemo_manual.txt)する前にバグや操作ミスで別画面に行ったりすると作業が消し飛ぶので非常にしんどいです。
なので、天体を選択するたびに都度自動でmemo.txtもしくはmemo_manual.txtを出力するようにした方が良いと思います。(オートセーブ)

僕もさっき30分強の作業が消し飛びました。。。

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
こちらもslackに載せさせて頂きました。
確認をお願い致します。

**Comment by COIAS-program** [comment]
@AnbaiAnbai
ご対応いただきありがとうございます。
手動測定モードにてクリック毎にmemo_manual.txtが書き出され、番号と座標の情報が保存されていることを確認いたしました。

同様の仕組みを、探索モードにも組み込んでいただけないでしょうか?
すなわち、探索モードにてノイズと天体を見分ける時に、画面をクリックするごとに[memo.txt](https://github.com/coias/coias-front-app/files/8973960/memo.txt)を書き出す。
memo.txtは探索モードにて四角を赤色にした天体のH番号を一列に書き出したものです。(下記添付ファイルを参照)
[memo.txt](https://github.com/coias/coias-front-app/files/8974042/memo.txt)
赤色は再クリックすると黒色に戻して選択を取り消せるので、毎回赤い天体のH番号をmemo.txtに新規上書きする形で全部更新すると良いと思います。

また、手動測定モードでも、memo_manual.txtが自動で書き出されはしますが、画面を再読み込みするとmemo_manual.txtに記載の天体は画面に表示されません。
これだと自動保存の恩恵がかなり薄くなりますし、何より画面を閉じたり間違って遷移して戻ってきた時、前回の選択がわからなくなるので、2重で測定したりしてしまう可能性が高くなります。
手動測定モードの画面を開いた時、もしカレントディレクトリにmemo_manual.txtが存在したら、それを読み込んで全ての座標情報(4点の座標)などを保存し、画像にはH番号と共に(3, 4)カラム目の位置に四角を設置する、また右側のアコーディオンにもその内容を初めから追加しておく、というようにできないでしょうか?
少し面倒な実装ですが、可能ならお願いしたく思います。

同様に、探索モードを開いた時にも、もしカレントディレクトリにmemo.txtが存在したら、memo.txtに記載の天体の四角を初めから赤くしておき、かつ右側のチェックボックスにもチェックが入った情報になっていると嬉しいです。

長くなってしまい申し訳ありませんが、まとめると、探索モードの画面情報とmemo.txtの中身、手動測定モードの画面情報とmemo_manual.txtの中身、をそれぞれ必ず同期した状態にしてほしい、という要望になります。

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
ご確認ありがとうございました。
実装の概要理解させて頂きました。こちらはつまり、#59 に、さらに四角を設置するなどの機能を追加するという認識でよろしいでしょうか？

**Comment by COIAS-program** [comment]
@AnbaiAnbai 
すみません、別issueで同様の内容が既にあがっていましたね。。。
はい、#59の内容とセットで扱っていただければと思います。
四角の設置やアコーディオンの内容もmemo.txtやmemo_manual.txtと同期させる、ということになります。

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
いえとんでもないです。
仕様の詳細を把握させて頂きましたので、このまま実装してみます。
ありがとうございました。

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
お疲れ様です。
[fba32ef](https://github.com/coias/coias-front-app/commit/fba32efd5e62baa475a34fa706a64219cfc255ce)にて、#62 と #59 を対応させて頂きました。
確認をお願い致します。

**Comment by COIAS-program** [comment]
@AnbaiAnbai 
すみません、anbai-update-manualmodeブランチにて確認したところ、何も機能は実装できていないように見えるのですが。。。
ブランチは合っていますでしょうか?
意図が伝わっていないようでしたら、明後日木曜日の打ち合わせでお伝えできればと思います。

また、同ブランチの再描画モードにて、どうもdisp.txtの天体の四角が全て描画されているように見えます。
再描画モードではredisp.txtに記載の天体のみ表示が正しいです。
mainブランチでは正しい挙動のままなので、ご確認いただき修正をお願いします。

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
申し訳ございません。
オートセーブ用に用意したcoias-back-appを更新し忘れておりました。
更新しましたので、back-appの、mainをpullして再度お試しください。
お手数ですがお願い致します。

**Comment by COIAS-program** [comment]
@AnbaiAnbai 
ご連絡ありがとうございます。
・探索モードにおけるオートセーブは実装されていない。「再描画」ボタンを押さずとも天体をクリックするごとにmemo.txtの出力をお願いします。
・ただしmemo.txtが存在する時に、何処かへ行って探索モードに戻ったときや画面をリロードした時に、memo.txtの中身を読み込んで復元することが実装されていることは確認いたしました。
・再描画モードの挙動がやはりおかしい。再描画モードは、redisp.txtに記載の天体を、全て黒色の四角で描画し(=チェックボックスも外れたまま)、また選択は一切できないモードです。mainブランチの挙動は正しいはずなのでそちらをご参照の上ご修正ください。
・手動測定モードは完璧だと思います！リロード時のmemo_manual.txtの読み込みも正しくできていて、png <-> fits座標系間の変換も正しくできているようなので、特に問題ないと思います。使っていくと気になる点は出てくるかもしれませんが、手動測定モードのGUI部分についてはひとまず完成と言って良いかと思います。(少し揺れる現象はありますが。)

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
ご確認ありがとうございます。
探索モードにおけるオートセーブなのですが、先程back-app微修正しましたので最新のもので再度お試しいただければと思います。
よろしくお願い致します。

**Comment by COIAS-program** [comment]
@AnbaiAnbai 
pushをお願いしてもよろしいでしょうか?
back-appの最新のcommitが1時間前になっているのですが、、、

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
1時間前に、2度commitを行いましたので、自分の環境ですと、
front[anbai-update-manualmode], back[main]のどちらも最新commitでオートセーブがされているのですが、いかがでしょうか。
ご確認お願い致します。

**Comment by COIAS-program** [comment]
@AnbaiAnbai 
front[anbai-update-manualmode]側の最新commitが取り込めていませんでした。
これを取り込むことで再描画モードの挙動は正しくなりました。
ただし、私の環境でもback[main]は最新ですが、「「再描画」ボタンを押さずとも天体をクリックするごとにmemo.txtの出力をする」は実装されていません。
back[main]ではマージ操作が最新のcommitになっているのですが、合っていますでしょうか?

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
大変申し訳ございませんでした。
frontを更新しましたので、frontを最新のもの[ac28d73](https://github.com/coias/coias-front-app/commit/ac28d73ac8da4f900135447d44c1b17be621f561)でお試しください。

右側の、チェックボックスには対応していたのですが、天体クリックに対しては全く未対応でした。

お手数おかけいたしますが、ご確認のほどよろしくお願い致します。

**Comment by COIAS-program** [comment]
@AnbaiAnbai 
早速のご対応ありがとうございます。
すみません、チェックボックスでのオートセーブは見落としていました。。。
最新版にて探索モードの天体クリックでもオートセーブされていることを確認いたしました。

これにて、オートセーブ機能と手動測定モードについては一旦mainにマージしてしまっても良いかと思います。

もう少し色々試してみたいのですが、今週はあまり時間が取れなさそうなので、またこれらの機能については落ち着いてからテストを行おうと思います。
しかるのちにissueを閉じさせていただきます。

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
お忙しい中ありがとうございました。
よろしくお願い致します。

**Comment by COIAS-program** [comment]
すみません、一点気がつきました。(こういった要望は五月雨式に出てきてしまうので申し訳ありません。。。)
手動測定モードにて、天体を追加した際にオートセーブされるようになっていますが、天体を削除する時(天体の四角をクリックしてその四角だけ消す時と、右側のチェックボックスにて天体毎消す時)にもオートセーブしていただけるようにお願いしてもよろしいでしょうか?

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
ありがとうございます。
anbai-update-manualブランチで対応させて頂きました。
また、slackに記載のエラーも解消されたと思うので、ご確認をお願い致します。

**Comment by COIAS-program** [comment]
ご対応ありがとうございます。
消去時にもオートセーブされることを確認いたしました。

**Comment by COIAS-program** [comment]
確認完了しました。
issueを閉じます。
