### ISSUE TITLE
再測定(手動測定)モードのリロードについて

### ISSUE THREAD

**Issue by COIAS-program** [aizulab/coias-front-app#63]
再測定(手動測定)モードについて、探索/再描画モードを表示させている状態で再測定(手動測定)モードのボタンを押すと画像が表示されるのですが、上のURL欄を叩いてリロードすると画像が表示されなくなります。
まだ再測定(手動測定)モードについては実装中ですので今後のアップデートでご修正いただければと思いますが、リロード時にも正しく表示されるようにお願い致します。

ちなみに、オリジナルCOIASでは再測定(手動測定)モードで表示されるのは、画像＋redisp.txtに記載の天体の四角と名前です。
redisp.txtは探索モードを終えて再描画モードに遷移をしなければ出力されませんので、再描画モードを介さずに再測定(手動測定)モードに移行した場合はエラーを出すようにした方が良いと思います。

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
こちらの機能を最新のanbai-update-manualmodeにて実装致しましたので、確認をお願い致します。
デモ動画は、slackにあげさせて頂きます

**Comment by COIAS-program** [comment]
@AnbaiAnbai 
ご対応いただきありがとうございます。
手動測定モードにてクリック毎にmemo_manual.txtが書き出され、番号と座標の情報が保存されていることを確認いたしました。

同様の仕組みを、探索モードにも組み込んでいただけないでしょうか?
すなわち、探索モードにてノイズと天体を見分ける時に、画面をクリックするごとにmemo.txtを書き出す。
memo.txtは探索モードにて四角を赤色にした天体のH番号を一列に書き出したものです。(下記添付ファイルを参照)
[memo.txt](https://github.com/coias/coias-front-app/files/8973960/memo.txt)
赤色は再クリックすると黒色に戻して選択を取り消せるので、毎回赤い天体のH番号をmemo.txtに新規上書きする形で全部更新すると良いと思います。

また、手動測定モードでも、memo_manual.txtが自動で書き出されはしますが、画面を再読み込みするとmemo_manual.txtに記載の天体は画面に表示されません。
これだと自動保存の恩恵がかなり薄くなりますし、何より画面を閉じたり間違って遷移して戻ってきた時、前回の選択がわからなくなるので、2重で測定したりしてしまう可能性が高くなります。
手動測定モードの画面を開いた時、もしカレントディレクトリにmemo_manual.txtが存在したら、それを読み込んで全ての座標情報(4点の座標)などを保存し、画像にはH番号と共に(3, 4)カラム目の位置に四角を設置する、また右側のアコーディオンにもその内容を初めから追加しておく、というようにできないでしょうか?
少し面倒な実装ですが、可能ならお願いしたく思います。

同様に、探索モードを開いた時にも、もしカレントディレクトリにmemo.txtが存在したら、memo.txtに記載の天体の四角を初めから赤くしておき、かつ右側のチェックボックスにもチェックが入った情報になっていると嬉しいです。

長くなってしまい申し訳ありませんが、まとめると、探索モードの画面情報とmemo.txtの中身、手動測定モードの画面情報とmemo_manual.txtの中身、をそれぞれ必ず同期した状態にしてほしい、という要望になります。

**Comment by COIAS-program** [comment]
@AnbaiAnbai 
(書き込む場所を間違えましたのでさっきのコメントは削除して再度書き込みます)
リロードした時にもredisp.txtの内容が表示され、またredisp.txtが無い状態で手動測定モードに遷移しようとした時にはエラーが出ることを確認いたしました。
こちらのissueは問題なく思いますので、issueを閉じさせていただきます。
