### ISSUE TITLE
手動測定モードで3点を選ぶ時に画像の外を選べてしまう問題

### ISSUE THREAD

**Issue by COIAS-program** [aizulab/coias-front-app#65]
GUI COIASにもオリジナルCOIASの独自GUIにも共通の問題なので、備忘録のためにこちらに記載します。

手動測定モードで画像をクリックして拡大画像を開く時、画像の端をクリックすると、画像の外側も写り込む拡大画像が表示される。
それそのものは問題ではないが、拡大画像で3点を選ぶ時に画像の外側が選べてしまい、memo_manual.txtに画像の外側の無効な座標が書き出されてしまう。
画像の外側の無効な座標でその後の解析をすると明らかにエラーになるので防がなくてはいけない。
memo_manual.txtに書き出す4点(x, yで値は合計8個)が画像の外側(=負の値かx, y方向のピクセルの最大値より大きい)の値になっているかチェックし、その場合は再選択するように促す機能が必要。

<img width="1343" alt="スクリーンショット 2022-07-01 21 11 04" src="https://user-images.githubusercontent.com/86390904/176891998-d56af719-ae35-4a7b-8270-c7bb7c026f17.png">
<img width="1385" alt="スクリーンショット 2022-07-01 21 11 25" src="https://user-images.githubusercontent.com/86390904/176892012-b284917c-8a2a-4ec0-b02c-d801d56f8e1d.png">

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
コミット : [728e0c4](https://github.com/coias/coias-front-app/commit/728e0c4554ce7cdd7f698c3ae3baa9f143f33ff9)
ブランチ : anbai-update-manualmode
にて、範囲外の場合はモーダルでアラートを出すように修正しました。
ご確認をお願い致します。

**Comment by COIAS-program** [comment]
@AnbaiAnbai 
デモ動画を確認し、自分でも動かしてみました。
基本的な実装はこれで大丈夫だと思います。
ただ、アラートを出す基準がよくわからないのと、3点選んだ時に画像の外を選んだ場合memo_manual.txtに書き出す際に画像内になるように補正してから出力していますかね?

私の意図としては、「選んだ3点のうち1つでも画像の外ならばアラートを出して再入力を促す」というものになります。
その方向でご修正いただければと思います。

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
デモ動画の確認ありがとうございます。

> 選んだ3点のうち1つでも画像の外ならばアラートを出して再入力を促す

について認識のズレがありましたので、最新版にてそのように修正させて頂きました。

またこれはなかなか珍しい例だと思うのですが、デモの動画のように、選んだ3点の1点が外側だが、その後に作成される四角形の4点は内側に入っているパターンも許容しているのですが、これはこれで問題ないと思っているのですがいかがでしょうか。

確認をお願い致します。

https://user-images.githubusercontent.com/97570265/177280616-65ca4630-59d7-4604-8d9a-f22ffaed3afd.mov

**Comment by COIAS-program** [comment]
@AnbaiAnbai 
実際のphotometryに使うのは描画された四角形なので、ご指摘の通り選んだ3点のうち1つが画像の外に出ていても、四角形が画像の範囲内に入っていれば問題ないと思います。
この実装で問題ないと思います。

バックエンド側独自GUIでも同様の実装を行いましたので、このissueを閉じさせていただきます。
