### ISSUE TITLE
手動測定モードの上書き防止についての要望

### ISSUE THREAD

**Issue by COIAS-program** [aizulab/coias-front-app#66]
ある天体ある画像についてすでに選んだことがあっても、その四角の外側をクリックしたら、「すでに測定されていますが再測定しますか?」と聞くようにしてから再度拡大画像を開いて測定させるようにお願いしたいです。
(四角の内側をクリックしたら「消しますか?」と聞かれる仕様はそのままで大丈夫です)

というのも、自分で真面目に手動測定してみて気がついたのですが、とある天体について測定し終わって次の天体を探していると、手動測定に熱中するあまり右のアコーディオンを新たに開き忘れて上書きしてしまうことが何度もあったからです。

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
ご要望ありがとうございます。
コミット : [728e0c4](https://github.com/coias/coias-front-app/commit/728e0c4554ce7cdd7f698c3ae3baa9f143f33ff9)  
ブランチ : anbai-update-manualmode
にて、ご要望の通りに実装させて頂きました。

ですので、現在手動測定のクリック時の挙動としては以下３パターンとなります。

1. 未選択の場合、そのまま3点選択へ
2. 選択済みで、その天体をクリックすると確認後に削除
3. 選択済みで、その天体以外をクリックすると確認後に更新

ご確認をお願い致します。

**Comment by COIAS-program** [comment]
@AnbaiAnbai 
確認致しました。
要望通りに実装されていると思います、ありがとうございました。

一点だけ、3.で更新をした直後に画像からフォーカスが外れ、左右キーとsキーの入力が入らない状態になります。
フォーカスが外れないようにお願い致します。

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
ご確認ありがとうございます。
フォーカスが外れないように修正させて頂きましたのでご確認お願い致します。

**Comment by COIAS-program** [comment]
@AnbaiAnbai 
修正確認致しました。
これで問題ないと思いますので、issueを閉じさせていただきます。
