### ISSUE TITLE
「探索/再描画」と「手動測定/名前修正」の部分のデザイン改善

### ISSUE THREAD

**Issue by AnbaiAnbai** [aizulab/coias-front-app#67]
現状、「探索/再描画」と「手動測定/最終確認」とすべき機能が揃っているが、これだと長いため「探索」と「手動測定」のように短くしたい。
しかし、これだと再描画、最終確認が必ず行わなければならないプロセスであることが分かりにくいため、ヘッダーと再描画周りのデザインから改善する。

**Comment by COIAS-program** [comment]
関連して、レポートモードボタンを有効にするか? それとも再描画モードおよび手動測定の再描画モードの「探索終了」ボタンからのみからしかレポートモードに行けないようにするか? の議論が必要。
さらに関連して、探索準備モードを行っていない状態で探索モード及び手動測定モードに行けないようにする機能の議論も必要。
(できればここら辺の機能は統一的にできたら分かりやすくて良い)

> 確かに、いつでもどこからでもレポートモードにいけてしまうとアラートを出す余計な手間がかかってしまうので、行ける箇所はなるべく限定して、「探索終了」もしくは「手動測定終了」のみからしかいけないようにした方が良いかもしれません。
> ただ、探索/再描画モードを終えた後に手動測定モードに行く時は上の「手動測定」ボタンから行くので、それと同様にレポートモードに行けた方が良いかとも思います。
> (探索モード、手動測定モード共に上のボタンから行けるのに、レポートモードだけそれでは行けないというのは違和感があります)
> ここら辺、他の部分の問題が一通り解決したら、またお打ち合わせをいただいてフローをもう一度整理した方が良いと思いました。

**Comment by COIAS-program** [comment]
この議論をさらに単純化すると、現状では他のモードに遷移するのに2通りやり方があります。

1. 画面上のモードボタンを押す
2. モード内の「探索終了」、「手動測定終了」を押す

現状この2つが混じっていますが、個人的にはどちらに統一をした方が良いと思います。

1.に統一をするのならば
- 「探索終了」と「手動測定終了」ボタンは削除してしまう
- 上のモードボタンでいつでもどこでも行けるようにする
- ただし、そのモードで必要となるファイルがカレントディレクトリに無い場合、そのモードに行ってもエラーモーダルを出して直前のモードに差し戻すか、鍵マーク＋カーソルを合わせても反応せずそのモードに行けないようにする、などの処置が必要。(必要なファイルがあるならば鍵をなくし、カーソルを合わせると明るくなって、かつクリックするとそのモードに行ける)
- ユーザーの自由度が高い実装

2.に統一をする場合を考えてみましたが、厳密にやるのならば上のモードボタンは完全なお飾りでモード内のボタンのみでモード遷移することになりますが、その場合、
- 探索準備モードに「探索モードに行く」ボタンを追加しなければいけない
- 手動測定を明示的に飛ばせない。やるなら再描画モードに「レポートモードに行く」と「手動測定モードに行く」ボタンの2つがいる
- 手動測定モードやレポートモードに行った時に自由に探索モードなどに戻れなくなる。できるようにするならそれぞれボタンをさらに追加するようにする
というようになって、ユーザーの自由度を完全に縛るか、自由度を担保するならボタン迷路状態にしなければいけないことがわかります。

そのため、1.に統一をした方が良いかと思います。
ただこれは個人的な意見なので、やはり一度議論させていただきたく思います。

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
ご意見ありがとうございます。
自分も1に統一したほうが、画面上のモードボタンが果たすべき責務の観点からも、直感的でいいと思います。
ただ、１を採用する場合のデザインの最適化は一旦議論させていただいた上で、案としてデザインを別ブランチで提供させていただければと思います。

**Comment by COIAS-program** [comment]
デザイン修正は基本的に完了していると思いますので、issueをクローズ致します。
