### ISSUE TITLE
全自動処理のプロセスを変更

### ISSUE THREAD

**Issue by Mizunanari** [aizulab/coias-front-app#7]
# 全自動処理のプログレスバーのようなものを表示

全自動処理がどこまで終了したか、またはどこで処理が止まってしまったかを確認するためのものが欲しいとのこと。
AstsearchRを実行するのではなく、下記を参考にAPIをひとつずつ実行し、フロントアプリに反映する。

AstsearchR

```bash
#!/bin/bash
preprocess
startsearch2R
prempsearchC
astsearch_new
```

## 実装例

* [React-Bootstrap · placeholders](https://react-bootstrap.netlify.app/components/placeholder/#placeholders)

**Comment by daiyokoyama** [comment]
902053f3a8f3ad18ce89a795354678aada3405ff
