### ISSUE TITLE
ブリンク機能の表示間隔のデフォルト値が短い

### ISSUE THREAD

**Issue by kn1cht** [aizulab/coias-front-app#79]
探索，測定の画面で画像のブリンク表示ができますが，表示間隔のデフォルト値が現在0.01秒となっています．

https://github.com/coias/coias-front-app/blob/50b83ec30bf40c217e99cbde41876ec8c22cb78b/src/component/model/MeasurementCommon/PlayMenu.jsx#L35-L39

試用していて，0.01秒間隔での切り替えは速すぎて天体の動きの把握が難しいです．また，観測画像のわずかな明度差によって激しい点滅が起きるため，目にもよくなさそうです．
従って，もっと長い間隔をデフォルトにしてもよいのではないかと考えます（個人的には0.1秒間隔がちょうどよいと感じました）．

**Comment by COIAS-program** [comment]
はい、同意です。
浦川さんが高速ブリンクで探すときに使っているので0.01秒は残した方が良いと思いますが、
僕も0.01秒は速すぎるのでいつも使っておらず、0.5秒でやっています。
ただ、0.5秒だと少し遅すぎるので、0.25秒とかがあった方がありがたいと思いました。
その上で、デフォルトを0.1秒か0.25秒にするのが良いと思います。(どちらにするかはお任せします)

**Comment by COIAS-program** [comment]
@kn1cht 
すみません、issueを発行した人間が内部の者だと勘違いしていました。。。
修正致しますのでしばらくお待ちください。

**Comment by kn1cht** [comment]
いえいえ，紛らわしい投稿の仕方で失礼致しました……！　ご検討いただけましたら幸いです．

**Comment by COIAS-program** [comment]
@kn1cht 
コード読み直して今気がついたのですが、そもそもここでセットしているsec変数はsetInterval()関数の第二引数にそのまま渡されているのですが、setInterval()関数の第二引数は関数呼び出しの間隔をms単位で入れることになっているので、現状のデフォルトでは0.01ms間隔でブリンクされるようになっていますね。。。
結構致命的なミスだったので、ご指摘いただけてよかったです。

さて、デフォルトのブリンク間隔を0.25秒になるように変更してmainブランチにpushしました。
念のためご確認いただいてもよろしいでしょうか?
ちなみに先ほどのマージで探索準備モード(とレポートモード)での解析の進捗率が画面に出るようになっているはずなので、そちらも合わせて見ていただければと思います。(バグが出るかもしれませんが)

**Comment by kn1cht** [comment]
@COIAS-program ご対応ありがとうございます．0.01msは速すぎますねｗ（先日試用した際は初手から0.1秒を選んでいたため気づきませんでした）

手元でも0.25秒がデフォルトになっているのを確認できました．進捗率表示も便利ですね 👍

**Comment by COIAS-program** [comment]
@kn1cht 
ご確認いただきありがとうございます。
それではこのissueを閉じさせていただきます。
また何かお気づきの点がありましたらお知らせください〜
