### ISSUE TITLE
探索画面・手動測定画面における操作UIの用意

### ISSUE THREAD

**Issue by kn1cht** [aizulab/coias-front-app#84]
探索/再描画画面では様々な操作が可能ですが，その中にキーボードショートカットでのみ可能な操作があります．
COIASに不慣れなユーザが気づかない可能性がありますので，見える形のUIを用意するためのissueです．

## 操作内容の整理

キーボード操作が可能でGUIがないのは，画像の拡大縮小以外にはなさそうです．

|                        	| GUI                    	| キーボード  	|
|------------------------	|------------------------	|-------------	|
| 画像の拡大縮小         	| **なし**               	| up, down    	|
| ブリンク               	| 再生・停止ボタン       	| S           	|
| コマ送り               	| コマ送りボタン（左右） 	| left, right 	|
| 表示設定モーダル       	| 歯車アイコン           	|             	|
| 選択モード             	| 矢印アイコン           	|             	|
| 天体の枠の表示・非表示 	| 非表示ボタン           	|             	|
| 輝度、コントラスト     	| スライダー             	|             	|
| 再描画                 	| 再描画ボタン           	|             	|

**Comment by COIAS-program** [comment]
拡大縮小のGUIボタンを設置する変更は見た感じ僕の方で十分に対応可能だと思いますので、こちらでやらせていただこうと思います。

**Comment by AnbaiAnbai** [comment]
@kn1cht (@COIAS-program 
ご確認とご指摘ありがとうございます。
https://github.com/coias/coias-front-app/pull/86#issuecomment-1354344143
こちらのプルリクにて、ボタンやスライドバーのレイアウトの改修で対応させていただきました。ご確認をお願いいたします。

**Comment by kn1cht** [comment]
ありがとうございます！　すっきりして見やすくなったと思います。
