### ISSUE TITLE
全自動処理・手動処理選択とデータ更新ボタンの表示場所の検討

### ISSUE THREAD

**Issue by kn1cht** [aizulab/coias-front-app#88]
# 概要
- 現在「ファイルアップロード」モーダルに表示されている「全自動処理・手動処理」選択のボタンと「小惑星データ更新」ボタンを、モーダル外に移すことを提案します。
- 提案理由は、① これら2つの機能は画像ファイルのアップロードとは独立であること、② 想定されている操作内容と順序が不明確であること　です。

# 現状
- 「ファイルアップロード」モーダル内に「全自動処理・手動処理」選択ボタンと「小惑星データ更新」ボタンがあります。
　　- ![](https://arcspace.jp/lib/exe/fetch.php?w=600&tok=2f1035&media=ja:coias:image013.png)
- 「全自動処理・手動処理」選択ボタンを切り替えると、探索準備画面のボタンが自動と手動で入れ替わります。これはファイルアップロード前でも後でも同様の挙動を示します。
- 「小惑星データ更新」ボタンを押すと、データ更新が行われます。これもファイルアップロード前でも後でも同様の挙動を示します。

# 考えられる現状の問題
## これら2機能は画像ファイルのアップロードとは独立であること
処理が自動か手動かを選ぶこと、小惑星データを更新することは画像ファイルアップロードとは独立の操作です。従って、これらの機能にアクセスする手段が「ファイルアップロード」モーダルにあるのは奇妙に感じます。

また、前項のとおり、これらの機能はファイルアップロード前でも後でも操作でき、起きる結果も同じです。ファイルアップロードと独立した機能なのであれば、モーダルの外にUIを移すべきではないかと考えます。

## 想定されている操作内容と順序が不明確であること
モーダル内にUIがあると、ユーザは「アップロードまでにこれらを全て操作する必要がある」と考える可能性があります。しかし、実際には、2つの機能は操作しなくてもファイルのアップロードが可能です。他方、「小惑星データ更新」ボタンを押してしまうとモーダルが一旦閉じて更新に入ってしまいます。これはユーザの期待に反する挙動になりえます。

操作の順序としては、1: ファイルのアップロード→ 2: 全自動処理・手動処理の選択→ 3: （オプション）小惑星データ更新 の順であると考えてよろしいでしょうか？

# 提案
- 「全自動処理・手動処理」選択ボタンと「小惑星データ更新」ボタンを、探索準備画面に移したいです。
- 一例として、下の画像のようなイメージです。
    - ![image](https://user-images.githubusercontent.com/16277200/207400436-5f795558-2cad-401d-8d69-04d890ebf734.png)
- 想定する操作順にUIが左上から右下に向かって並び、さらに必須でない操作は最下部に来るようになっています。

**Comment by COIAS-program** [comment]
ご意見ありがとうございます。
概ね同意です。

> 操作の順序としては、1: ファイルのアップロード→ 2: 全自動処理・手動処理の選択→ 3: （オプション）小惑星データ更新 の順であると考えてよろしいでしょうか？

1.と2.についてはその順序だと思います。ただし3.については仰る通り完全にオプショナルで、特にwebCOIASではサーバーが勝手に更新をかけるのでユーザーが手動で更新をすることはないと思います。
そう思うと、3.はなるべく見えないところに隠しておくほうが良いと思います。(例えばパタメータ設定モーダル(|||に横線が入ったアイコン)の中?)
ただしデスクトップCOIASでは自動更新の機能はなくユーザーが小惑星データの更新をしないといけないので悩ましいところですが。。。
(現実問題として将来的にデスクトップCOIASを実践的に使っていく人はほとんどいないと思うので、webCOIASでのデザイン優先で改善していくのが良いと思います)

**Comment by AnbaiAnbai** [comment]
@kn1cht @COIAS-program 
お疲れ様です。
ご提案ありがとうございます。

このissueに関しては、将来的にデスクトップCOIASとWeb COIASを二つとも運用していくのか否かによると思います。
案ですが、

- 二つとも運用していく場合
  - レポジトリをWeb版、デスクトップ版にきりの良いところで分けてしまう？
- Web COIASのみ運用していく場合
  - 「ファイル」、「小惑星データ更新」ボタンを消してしまう

いずれにせよ、将来的にデスクトップCOIASとWeb COIASを二つとも運用していくのか否かを決めるべきだと思います。

**Comment by COIAS-program** [comment]
これは僕の備忘録です。
小惑星データ更新ボタンを残す場合、最後に更新した日時分を小惑星更新ボタンの下に表示させたい。

**Comment by COIAS-program** [comment]
@AnbaiAnbai @kn1cht 
webCOIASでも、cronが機能していない時など手動で「小惑星データ更新」をしたいこともあるかと思いますので、ボタン自体は残しておきたいと考えています。(ただし使うことは少ないのでパラメータ設定モーダルの中とかに入れておくとか)
一方「ファイル」ボタンに関しては、画像の選択方法がwebCOIASでは大きく変わるので、ボタンではなく別の方法(専用ページとか?)が適していると思います。(「ファイル」ボタンから画像選択ページなりモーダルなりに飛ぶという選択肢はあるかもしれませんが)
なのでwebCOIASにおいて「ファイル」ボタンを消してしまうことには同意です。

デスクトップCOIASとwebCOIASの使い分け・運用をどうするのかは、少し別のトピックなのでslackに書かせていただきます。
